name: nutriapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.2
  flutter_spinbox: ^0.6.0
  provider: ^6.0.1
  spinner_input: ^0.1.2
  flutter_native_splash: ^1.3.1
  splashscreen: ^1.3.5
  animate_do: ^2.0.0
  intl: ^0.17.0
  smooth_page_indicator: ^1.0.0+2
  fl_chart: ^0.40.2
  fluttertoast: ^8.0.8
  rflutter_alert: ^2.0.4
  # share: ^2.0.4
  # wc_flutter_share: ^0.4.0
  # dio: ^4.0.4
  path_provider: ^2.0.8
  share_plus: ^3.0.4
  
  # fluttertoast: ^8.0.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"
  
flutter_icons:
  android: true 
  ios: true
  image_path: "assets/imagenes/logo.png"

flutter:

  uses-material-design: true
  assets: 
    - assets/imagenes/
  fonts:
    - family: genostff
      fonts:
        - asset: assets/fonts/Genos-Black.ttf
        - asset: assets/fonts/Genos-BlackItalic.ttf
        - asset: assets/fonts/Genos-Bold.ttf
        - asset: assets/fonts/Genos-BoldItalic.ttf
        - asset: assets/fonts/Genos-ExtraBold.ttf
        - asset: assets/fonts/Genos-ExtraBoldItalic.ttf
        - asset: assets/fonts/Genos-ExtraLight.ttf
        - asset: assets/fonts/Genos-ExtraLightItalic.ttf
        - asset: assets/fonts/Genos-Italic.ttf
        - asset: assets/fonts/Genos-Light.ttf